name: Create Archive
on: 
 push:
  branches:
  - main
      
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Rename file 
      run: mv Tois* pack.zip
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "pack.zip"
