name: Create Archive
on: 
 push:
  branches:
  - main
      
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Rename file 
      run: mv Tois* pack.zip
    - name: set time
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "pack.zip"
        tag: ${{ env.CURRENT_DATETIME }}
