on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto Deploy via ssh
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 153.127.10.13
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          post: 22
          script: |
            cd /home/ubuntu/web/devbase-resourcepack
            git pull
            zip build/pack.zip assets/ pack.mcmeta pack.png
